### ISSUE TITLE
phpBB 3.1.5

### ISSUE THREAD

**Issue by Galixte** [proycon/unilangforum#17]
Hi @proycon,

this repository provides phpBB 3.1.3 and three extensions. If i download only those extensions https://github.com/proycon/unilangforum/tree/master/phpBB3/ext/unilang (without phpBB 3.1.3 files) and i put them in my board phpBB 3.1.5, it will work ?

**Comment by proycon** [comment]
Yeah, that should work fine.

**Comment by Galixte** [comment]
Thanks !
