### ISSUE TITLE
Migrate langicon.php from old site to current one 

### ISSUE THREAD

**Issue by proycon** [proycon/unilangforum#21]
langicon.php is extensively used in bbcode for flags. The forum still references the old www.unilang.org version as there is no replacement yet (I think).

**Comment by proycon** [comment]
Implemented, now only the BBCode need to adapt to forum.unilang.org/langicon.php

**Comment by lromao** [comment]
Thanks! 
I just changed the BBCode and it works perfectly now :)

**Comment by proycon** [comment]
Great! :)

**Comment by lromao** [comment]
Perhaps wikidirect.php should be migrated as well? It doesn't seem to be working for any new languages either. Not that it's as important as flags showing up, but just to let you know...

**Comment by proycon** [comment]
Hmm, right, I'll have to find out what that was for again..

**Comment by lromao** [comment]
@proycon : I'm not sure how this was before, but the logic on the migrated langicon.php seems to be somewhat simplified (compare with the langicon function on lang_functions.php). 
The major effect is that complex languages based on countries stopped working (e.g. en-US, pt-BR)
I'm not sure if the other function can be reused (PHP is not exactly my forte), so I tried to implement a quick fix by detecting if a language code follows this pattern and send it to the country flag instead (pretty much the logic that existed before)
However, the whole thing breaks whenever I add that condition. I left it commented at the moment and would appreciate if you (or anyone else who understands PHP better than me) can have a look :) Thanks

**Comment by lromao** [comment]
Fixed.
I turns out there was some freaking invisible character on that line that was causing a syntax error (note to self: use a proper IDE)

**Comment by proycon** [comment]
Ah! Great that you managed to find it already :)
